# Generated by Django 5.2 on 2025-04-17 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Schedule Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom (Cron)')], default='daily', max_length=20)),
                ('cron_expression', models.CharField(blank=True, help_text='Cron expression for custom schedules (e.g., "0 8 * * 1" for every Monday at 8 AM)', max_length=100, null=True)),
                ('run_at_hour', models.PositiveSmallIntegerField(blank=True, help_text='Hour (0-23)', null=True)),
                ('run_at_minute', models.PositiveSmallIntegerField(blank=True, help_text='Minute (0-59)', null=True)),
                ('run_on_days', models.JSONField(blank=True, default=list, help_text='Days to run on for weekly schedules (0=Monday, 6=Sunday)')),
                ('run_on_day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Day of month to run on (1-31)', null=True)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Schedule',
                'verbose_name_plural': 'Workflow Schedules',
                'ordering': ['workflow__name', 'name'],
            },
        ),
    ]
