# Generated by Django 5.2 on 2025-04-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='trigger_type',
            field=models.CharField(choices=[('none', 'None'), ('client', 'Client'), ('event', 'Event')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='edges',
            field=models.JSONField(default=list, verbose_name='Workflow Edges'),
        ),
    ]
