# Generated by Django 5.2 on 2025-04-15 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('plan_type', models.CharField(choices=[('one_time', '일반결제'), ('weekly', '매주결제'), ('monthly', '매월결제')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('krw', 'KRW'), ('usd', 'USD')], default='krw', max_length=3)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('software', '소프트웨어'), ('hardware', '하드웨어'), ('service', '서비스'), ('subscription', '구독'), ('other', '기타')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
