# Generated by Django 5.2 on 2025-04-16 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Industry Code')),
                ('name', models.CharField(max_length=200, verbose_name='Industry Name')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporation_number', models.CharField(max_length=13, verbose_name='Corporation Number')),
                ('business_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Business Number')),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner/CEO')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('homepage', models.JSONField(blank=True, null=True, verbose_name='Website URLs')),
                ('employee', models.IntegerField(default=1, verbose_name='Number of Employees')),
                ('revenue', models.BigIntegerField(blank=True, null=True, verbose_name='Annual Revenue')),
                ('address', models.TextField(blank=True, null=True)),
                ('si_nm', models.CharField(blank=True, max_length=50, null=True, verbose_name='City/Province')),
                ('sgg_nm', models.CharField(blank=True, max_length=50, null=True, verbose_name='District')),
                ('established_date', models.DateField(blank=True, null=True)),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.industry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('corporation_number', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LeadList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='List Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('leads', models.ManyToManyField(blank=True, related_name='lead_lists', to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOneLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation_number', models.CharField(max_length=13, unique=True, verbose_name='Corporation Number')),
                ('business_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Business Number')),
                ('industry_name', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('name_eng', models.CharField(blank=True, max_length=200, null=True, verbose_name='English Name')),
                ('owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner/CEO')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('homepage', models.JSONField(blank=True, null=True, verbose_name='Website URLs')),
                ('handle_goods', models.JSONField(blank=True, null=True, verbose_name='Products/Services')),
                ('employee', models.IntegerField(default=1, verbose_name='Number of Employees')),
                ('finance_currency_code', models.CharField(blank=True, max_length=5, null=True)),
                ('finance_year', models.IntegerField(blank=True, null=True)),
                ('finance_revenue', models.BigIntegerField(blank=True, null=True)),
                ('finance_operating_profit', models.BigIntegerField(blank=True, null=True)),
                ('finance_comprehensive_income', models.BigIntegerField(blank=True, null=True)),
                ('finance_net_profit', models.BigIntegerField(blank=True, null=True)),
                ('finance_total_assets', models.BigIntegerField(blank=True, null=True)),
                ('finance_total_liabilities', models.BigIntegerField(blank=True, null=True)),
                ('finance_total_equity', models.BigIntegerField(blank=True, null=True)),
                ('finance_capital', models.BigIntegerField(blank=True, null=True)),
                ('finance_debt_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_normal_taxpayer', models.BooleanField(default=False)),
                ('is_corporation', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('si_nm', models.CharField(blank=True, max_length=50, null=True, verbose_name='City/Province')),
                ('sgg_nm', models.CharField(blank=True, max_length=50, null=True, verbose_name='District')),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scraped_bizinfo', models.BooleanField(default=False)),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesone_leads', to='leads.industry')),
                ('keywords', models.ManyToManyField(blank=True, related_name='ultimatedb', to='leads.keyword')),
            ],
        ),
    ]
