# Generated by Django 5.2 on 2025-04-16 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_search_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadImportTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(max_length=50, unique=True, verbose_name='Celery Task ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Original File Name')),
                ('file_type', models.CharField(max_length=10, verbose_name='File Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0, verbose_name='Total Records')),
                ('imported_records', models.IntegerField(default=0, verbose_name='Imported Records')),
                ('error_records', models.IntegerField(default=0, verbose_name='Error Records')),
                ('errors', models.JSONField(blank=True, null=True, verbose_name='Error Details')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lead_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_tasks', to='leads.leadlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_import_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Import Task',
                'verbose_name_plural': 'Lead Import Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
