# Generated by Django 5.2 on 2025-04-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_salesonelead_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='salesonelead',
            name='search_vector',
        ),
    ]
